import React from 'react';

export default function ResearchSummary({ summary, plan }) {
  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
      {plan && (
        <div className="card">
          <h3 className="section-title">🧠 Research Plan (AI Planner Agent)</h3>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16 }}>
            <div>
              <strong style={{ color: 'var(--text-muted)', fontSize: 12 }}>RESEARCH TOPIC</strong>
              <p style={{ marginTop: 4 }}>{plan.research_topic}</p>
            </div>
            <div>
              <strong style={{ color: 'var(--text-muted)', fontSize: 12 }}>RECOMMENDED SOURCES</strong>
              <div className="tags" style={{ marginTop: 6 }}>
                {(plan.recommended_sources || []).map(s => (
                  <span key={s} className="badge badge-blue">{s}</span>
                ))}
              </div>
            </div>
            <div>
              <strong style={{ color: 'var(--text-muted)', fontSize: 12 }}>KEY CONCEPTS</strong>
              <div className="tags" style={{ marginTop: 6 }}>
                {(plan.key_concepts || []).map(c => <span key={c} className="tag">{c}</span>)}
              </div>
            </div>
            <div>
              <strong style={{ color: 'var(--text-muted)', fontSize: 12 }}>SEARCH QUERIES</strong>
              <div style={{ marginTop: 6, display: 'flex', flexDirection: 'column', gap: 4 }}>
                {(plan.search_queries || []).map((q, i) => (
                  <span key={i} style={{ fontSize: 12, color: 'var(--text-muted)' }}>"{q}"</span>
                ))}
              </div>
            </div>
          </div>
        </div>
      )}
      {summary && (
        <div className="card">
          <h3 className="section-title">📝 AI Research Summary</h3>
          <div className="alert alert-info" style={{ margin: 0 }}>
            ℹ️ <strong>Transparency:</strong> This summary was generated by IBM watsonx.ai based on the abstracts and metadata of the retrieved papers.
          </div>
          <p style={{ marginTop: 12, lineHeight: 1.7, fontSize: 14, whiteSpace: 'pre-wrap' }}>{summary}</p>
        </div>
      )}
    </div>
  );
}
